language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2
  - 2.3.3
  - 2.4.1

branches:
  only:
    - master

script:
  - bundle exec rake style
  - bundle exec rake spec

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "CY1KDlAK2WpdeAzCIwbXjj7xG1kjdJhRg6hFDRPjZ6V6MzjJetq2heB65tP3d8ET8xeZ/fePg8//rNZADcvbjrW3lTcVtl+ov0EEkklhN1GLvwPT0iThB54Dmr6bFUujRn7IGoYNDJx9QBJidUbXG0yV83EqyGE8sd8ibANdmxE8wcUv6/vw8tkhGSA5ZOUZEzIa958w2tTUOS3ql6/nYqnlwyZdrbXxRWhmtfZ5/D6W57vCV8oB7GfZiXRBXnPpeKgCj96CxErEv11fzVMJXNKqX3NMlLwLR53Bamb3q3thxR0uhlk18Bz4ZrDci2VhB1La0odkXrP/2qX2e/2NN3voLI7vZaqq1yv7NSXG2vgLkYzRPUPsJiGcunUZCD2MLjTBfLTFswmDJfW0u1hqJG5G228Mz16lAYNexkziZtmRKi7M4RdG5zSKa/dFGwudO+8BreEfZtIcRC+RqxuBAFvfPVSTs5Cnb0/xz6RybqeEGrsGVO0qj5F0yubf5pIUpVK+uiRKY9V4DT+qjLpo5CmRETpw0ND94AazogtqGX7TIbH3bdKPs4u4CKOdYFMpLMLUWTwXsjR0aOFNGZh4KuNtCRoEmWuCflyIB2esDUAhpLt6VKUgK20A1AOV/LuidAmuQLeBySbdl6/yvQKTVLtSIz4ydA457DFHU8pKkRY="
